version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
  
  build:
    commands:
      - yarn build
      - yarn test

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
